# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['picture_cut.py'],
    pathex=[],
    binaries=[],
    datas=[('PictureCut.ico', '.')],
    hiddenimports=[
        'PIL.Image',
        'PIL.ImageOps',
        'PIL.ImageFilter',
        'PIL.ImageDraw',
        'PIL.ImageTk',
        'numpy',
        'windnd',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'rembg',
        'onnxruntime',
        'onnx',
        'scipy',
        'skimage',
        'pymatting',
        'pooch',
        'numba',
        'llvmlite',
        'jsonschema',
        'jsonschema_specifications',
        'tqdm',
        'torch',
        'tensorflow',
        'keras',
        'matplotlib',
        'pandas',
        'sympy',
        'IPython',
        'jupyter',
        'notebook',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='PictureCut',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='PictureCut.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='PictureCut',
)
